services:
  mysql:
    image: mysql:8.0
    container_name: mysql_todolist
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todonet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Default=server=mysql;port=3306;database=todolist;user=root;password=root
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mysql
    networks:
      - todonet

volumes:
  mysql-data:

networks:
  todonet:
